version: "3.8"
networks:
  flink-net:
    ipam:
      config:
        - subnet: 172.18.0.0/16
services:
  sql-client:
    container_name: 'sql-client'
    build:
      context: .
      dockerfile: sql-client/Dockerfile
    depends_on:
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
    volumes:
      - ./settings/:/settings
    networks:
      flink-net:
        ipv4_address: 172.18.0.11

  jobmanager:
    image: flink:1.17.1-scala_2.12-java11
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./settings/:/settings
      - ./data/:/data
    networks:
      flink-net:
        ipv4_address: 172.18.0.12

  taskmanager:
    image: flink:1.17.1-scala_2.12-java11
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
    volumes:
      - ./settings/:/settings
      - ./data/:/data
    networks:
      flink-net:
        ipv4_address: 172.18.0.13
  kafka:
    container_name: kafka
    image: erkansirin78/kafka:3.2.0
    build:
      context: ./kafka
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/data/kafka/
      - ./kafka/config/server.properties:/kafka/config/server.properties
    networks:
      flink-net:
        ipv4_address: 172.18.0.14